/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author julia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private Controlador controlador;
    
    
        
    
    public MenuPrincipal() {
        initComponents();
    }
    /*se crea la vista y se carga el controlador que se paso desde el main
    */
    public MenuPrincipal(Controlador ctr) {
        this();
        this.controlador = ctr;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelActual = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSolicitarTurno = new javax.swing.JMenuItem();
        itemColaDeTurnos = new javax.swing.JMenuItem();
        itemCancelarTurno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemAltaCliente = new javax.swing.JMenuItem();
        itemModificarCliente = new javax.swing.JMenuItem();
        itemEliminarCliente = new javax.swing.JMenuItem();
        itemListarClientes = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        itemTramite = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itemGestorDeClases = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemAreas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itemEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelActual.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Turno");

        itemSolicitarTurno.setText("Solicitar Turno");
        itemSolicitarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSolicitarTurnoActionPerformed(evt);
            }
        });
        jMenu1.add(itemSolicitarTurno);

        itemColaDeTurnos.setText("Cola de turnos");
        itemColaDeTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemColaDeTurnosActionPerformed(evt);
            }
        });
        jMenu1.add(itemColaDeTurnos);

        itemCancelarTurno.setText("Cancelar Turno");
        itemCancelarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCancelarTurnoActionPerformed(evt);
            }
        });
        jMenu1.add(itemCancelarTurno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        itemAltaCliente.setText("Añadir");
        itemAltaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltaClienteActionPerformed(evt);
            }
        });
        jMenu2.add(itemAltaCliente);

        itemModificarCliente.setText("Modificar");
        itemModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(itemModificarCliente);

        itemEliminarCliente.setText("Eliminar");
        itemEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(itemEliminarCliente);

        itemListarClientes.setText("Listar");
        itemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarClientesActionPerformed(evt);
            }
        });
        jMenu2.add(itemListarClientes);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Tramite");

        itemTramite.setText("GestorTramites");
        itemTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTramiteActionPerformed(evt);
            }
        });
        jMenu7.add(itemTramite);

        jMenuBar1.add(jMenu7);
        jMenuBar1.add(jMenu3);

        jMenu4.setText("GestorDeClases");

        itemGestorDeClases.setText("GestorDeClases");
        itemGestorDeClases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestorDeClasesActionPerformed(evt);
            }
        });
        jMenu4.add(itemGestorDeClases);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Area");

        itemAreas.setText("Gestionar Areas");
        itemAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAreasActionPerformed(evt);
            }
        });
        jMenu6.add(itemAreas);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Empleado");

        itemEmpleados.setText("GestorEmpleados");
        itemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadosActionPerformed(evt);
            }
        });
        jMenu5.add(itemEmpleados);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActual, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelActual, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSolicitarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSolicitarTurnoActionPerformed
        
        //cambia el panel del jframe por el de Solicitar Turnos
        SolicitarTurnos st = new SolicitarTurnos(controlador);
        cambiarPanel(st);
    }//GEN-LAST:event_itemSolicitarTurnoActionPerformed

    private void itemAltaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltaClienteActionPerformed
       AñadirCliente ac = new AñadirCliente(controlador);
        cambiarPanel(ac);
    }//GEN-LAST:event_itemAltaClienteActionPerformed

    private void itemColaDeTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemColaDeTurnosActionPerformed
        ColaDeTurnos panel = new ColaDeTurnos(controlador);
        this.cambiarPanel(panel);
    }//GEN-LAST:event_itemColaDeTurnosActionPerformed

    private void itemModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarClienteActionPerformed
   ModificarCliente mc = new ModificarCliente(controlador);
   this.cambiarPanel(mc);
    }//GEN-LAST:event_itemModificarClienteActionPerformed

    private void itemEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarClienteActionPerformed
       EliminarCliente ec = new EliminarCliente(controlador);
       this.cambiarPanel (ec);
    }//GEN-LAST:event_itemEliminarClienteActionPerformed

    private void itemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarClientesActionPerformed
        ListarClientes lc = new ListarClientes(controlador);
        this.cambiarPanel(lc);
    }//GEN-LAST:event_itemListarClientesActionPerformed

    private void itemGestorDeClasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestorDeClasesActionPerformed
      GestorDeClases gc = new GestorDeClases(controlador);
        this.cambiarPanel(gc);
    }//GEN-LAST:event_itemGestorDeClasesActionPerformed

    private void itemAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAreasActionPerformed
         Areas are = new Areas(controlador);
         this.cambiarPanel(are);
    }//GEN-LAST:event_itemAreasActionPerformed

    private void itemTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTramiteActionPerformed
       GestorTramites gt = new GestorTramites(controlador);
         this.cambiarPanel(gt);
    }//GEN-LAST:event_itemTramiteActionPerformed

    private void itemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadosActionPerformed
         GestionEmpleados ge = new GestionEmpleados(controlador);
         this.cambiarPanel(ge);
    }//GEN-LAST:event_itemEmpleadosActionPerformed

    private void itemCancelarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCancelarTurnoActionPerformed
        CancelarTurno  ct = new CancelarTurno(controlador);
         this.cambiarPanel(ct);
    }//GEN-LAST:event_itemCancelarTurnoActionPerformed
    
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAltaCliente;
    private javax.swing.JMenuItem itemAreas;
    private javax.swing.JMenuItem itemCancelarTurno;
    private javax.swing.JMenuItem itemColaDeTurnos;
    private javax.swing.JMenuItem itemEliminarCliente;
    private javax.swing.JMenuItem itemEmpleados;
    private javax.swing.JMenuItem itemGestorDeClases;
    private javax.swing.JMenuItem itemListarClientes;
    private javax.swing.JMenuItem itemModificarCliente;
    private javax.swing.JMenuItem itemSolicitarTurno;
    private javax.swing.JMenuItem itemTramite;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panelActual;
    // End of variables declaration//GEN-END:variables

private void cambiarPanel(JPanel panel) {
        panelActual.removeAll();
        panelActual.add(panel,BorderLayout.CENTER);
        panelActual.revalidate();
        panelActual.paintAll(getGraphics());
    }

}
